version: 2
updates:
  - package-ecosystem: "github-actions" # Check for updates to GitHub Actions dependencies
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub" # Check for updates to Dart packages monthly.
    directory: "/"
    schedule:
      interval: "monthly" #daily #monthly #weekly
